---
name: Testin
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Checkout
      uses: actions/checkout@v2

    - name: go get
      run: go get -v -t -d ./...

    - name: go test
      run: go test -v .

    - name: go build
      run: go build -v .

    - name: Testing
      run: |
        echo '{}' > package.json
        git add --force --ignore-errors package.json
        git commit -m "Testing"
        git tag plswork
        git push --tags https://mokrz:$GH_TOKEN@github.com/mokrz/testsvc.git HEAD:staging
      env:
        GH_TOKEN: "${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}"
