---
name: Testin
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: testing
      run: |
        wget https://github.com/containerd/containerd/archive/v1.3.4.zip
        unzip v1.3.4.zip 
