---
name: Test Workflow

on:
  push:
    branches: [ master ]

jobs:
  checkout:
    container:
      options: --rm
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
