---
name: Testin
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    
    - name: Download containerd
      run: curl -L --output /tmp/containerd-1.3.4.linux-amd64.tar.gz https://github.com/containerd/containerd/releases/download/v1.3.4/containerd-1.3.4.linux-amd64.tar.gz
    
    - name: Install/start containerd
      run: |
        sudo sh -c 'tar -xvz -f /tmp/containerd-1.3.4.linux-amd64.tar.gz -C /usr/local/ && mkdir -p /etc/containerd/ && containerd config default > /etc/containerd/config.toml was && chmod +x /usr/local/bin/containerd* /usr/local/bin/ctr'
        sudo containerd > /tmp/containerd.log &
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cat containerd logs
      run: cat /tmp/containerd.log
    
    - name: go get
      run: go get -v -t -d ./...
    
    - name: Run tests
      run: |
        sudo go test -v ./...


