---
name: Testin
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: testing
      uses: actions/http-client@master
      with:
        url: https://google.com
