---
name: Testin
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: testing
      run: |
        wget https://github.com/containerd/containerd/archive/v1.3.4.zip
        unzip v1.3.4.zip
        ls
        curl -L --output containerd-1.3.4.linux-amd64.tar.gz https://github.com/containerd/containerd/releases/download/v1.3.4/containerd-1.3.4.linux-amd64.tar.gz
        sudo tar -xvz -f containerd-1.3.4.linux-amd64.tar.gz -C /usr/local/bin/
        sudo sh -c 'containerd config default > /etc/containerd/config.toml'
        ls /usr/local/bin/
        cat /etc/containerd/config.toml
        
